name: Build Thorium ARM32

on:
  push:
    branches:
      - main

jobs:
  build-arm32:
    runs-on: windows-latest
    steps:
      # 1️⃣ Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Instalar dependencias básicas
      - name: Install dependencies
        run: |
          choco install -y visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.NativeDesktop --includeRecommended --passive --norestart"
          choco install -y python3 git

      # 3️⃣ Instalar depot_tools (para GN y Ninja)
      - name: Install depot_tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git C:\depot_tools
          echo "C:\depot_tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      # 4️⃣ Inicializar submódulos y dependencias de Thorium
      - name: Fetch Thorium dependencies
        shell: cmd
        run: |
          cd %GITHUB_WORKSPACE%
          fetch.bat thorium
          cd thorium
          git submodule update --init --recursive

      # 5️⃣ Generar archivos de build para ARM32
      - name: Generate build files with GN
        run: |
          cd thorium
          gn gen out\thorium --args="target_os='win' target_cpu='arm' is_debug=false"

      # 6️⃣ Compilar Thorium ARM32 con Ninja
      - name: Build Thorium
        run: |
          cd thorium
          autoninja -C out\thorium thorium_shell

      # 7️⃣ Subir el ejecutable como artefacto
      - name: Upload ARM32 artifact
        uses: actions/upload-artifact@v4
        with:
          name: thorium-arm32
          path: thorium\out\thorium\thorium_shell.exe
