name: Build Thorium ARM32

on:
  push:
    branches:
      - main

jobs:
  build-arm32:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Instalar dependencias básicas
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3 git clang lld cmake ninja-build pkg-config
          # Instalar wine para probar el .exe
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y wine32 wine64

      # 3️⃣ Instalar depot_tools (para GN y Ninja)
      - name: Install depot_tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git ~/depot_tools
          echo "$HOME/depot_tools" >> $GITHUB_PATH

      # 4️⃣ Inicializar submódulos y dependencias de Thorium
      - name: Fetch Thorium dependencies
        run: |
          cd $GITHUB_WORKSPACE
          ~/depot_tools/fetch thorium
          cd thorium
          git submodule update --init --recursive

      # 5️⃣ Generar archivos de build para ARM32
      - name: Generate build files with GN
        run: |
          cd thorium
          gn gen out/thorium --args="target_os=\"win\" target_cpu=\"arm\" is_debug=false"

      # 6️⃣ Compilar Thorium ARM32 con Ninja
      - name: Build Thorium
        run: |
          cd thorium
          autoninja -C out/thorium thorium_shell

      # 7️⃣ (Opcional) Probar que el .exe arranca en Wine
      - name: Test build with Wine
        run: |
          cd thorium/out/thorium
          wine ./thorium_shell.exe || true

      # 8️⃣ Subir el ejecutable como artefacto
      - name: Upload ARM32 artifact
        uses: actions/upload-artifact@v4
        with:
          name: thorium-arm32
          path: thorium/out/thorium/thorium_shell.exe
