name: Build ARM32 EXE

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y clang build-essential cmake

      - name: Compile ARM32 EXE
        run: |
          mkdir -p build
          clang -target armv7-windows-gnu -o build/programa_arm32.exe src/*.cpp

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: programa_arm32
          path: build/programa_arm32.exe
