name: Build Thorium ARM32

on:
  push:
    branches:
      - main

jobs:
  build-arm32:
    runs-on: windows-latest
    name: Build ARM32
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.NativeDesktop --includeRecommended --passive --norestart"
          choco install python3

      - name: Build Thorium for ARM32
        run: |
          # Aquí van los comandos específicos de compilación para ARM32
          # Por ejemplo, siguiendo la documentación oficial de Thorium:
          # git submodule update --init --recursive
          # python3 build.py --arch=armv7

      - name: Upload ARM32 artifact
        uses: actions/upload-artifact@v4
        with:
          name: thorium-arm32
          path: path\to\output\thorium_arm32.exe
