name: Build Thorium ARM32

on:
  push:
    branches:
      - main

jobs:
  build-arm32:
    runs-on: windows-latest
    name: Build ARM32
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.NativeDesktop --includeRecommended --passive --norestart"
          choco install python3

      - name: Set up environment
        run: |
          ./trunk.sh
          ./setup.sh --arm

      - name: Configure build arguments
        run: |
          gn args out\thorium
          # Asegúrate de configurar los argumentos correctamente

      - name: Build Thorium for ARM32
        run: |
          autoninja -C out\thorium thorium_shell

      - name: Upload ARM32 artifact
        uses: actions/upload-artifact@v4
        with:
          name: thorium-arm32
          path: out\thorium\thorium_shell.exe
